#!/bin/bash
localPATH=`pwd`
sep="---------------------------"
msg=""

CYAN='\033[0;36m'
NC='\033[0m'
RED='\033[0;31m'
projects=( "kong-api-gateway" "resource-adaptor" "resource-cataloguer" "data-collector" "resource-discoverer" "actuator-controller" )

verify () {
  if [ $? != 0 ]; then
    printf "${RED}$1${NC}"
    exit 2
  fi
}

if [ "$1" = "pull" ]; then
  echo $sep
  for d in "${projects[@]}"; do
    if [ "$d" != 'zPOO/' ]; then
      if [ -n "$(git -C $localPATH/$d status --porcelain)" ]; then
        msg="You have uncomitted changes on $d"
        printf "${RED}"
        echo $msg
        printf "${NC}"
        echo
      fi
    fi
  done

  if [ -n "$msg" ]; then
    echo $sep
    echo "Aborting..."
    echo
    exit 1
  else
    echo "All repositories are clean"
    echo "$sep"
    for d in "${projects[@]}"; do
      if [ "$d" != 'zPOO/' ]; then
        echo "Processing $d :"
        git -C $localPATH/$d checkout master
        printf "${CYAN}"
        echo $(git -C $localPATH/$d pull origin master)
        printf "${NC}"
      fi
    done
  fi
fi

if [ "$1" = "setup" ]; then
  # docker network create platform
  echo "Running migrations"
  docker exec -it interscity-resource-adaptor sh -c "rake db:setup"
  docker exec -it interscity-actuator-controller sh -c "rake db:setup"
  docker exec -it interscity-resource-cataloguer sh -c "rake db:setup"
  docker exec -it interscity-data-collector sh -c "rake db:setup"
fi

if [ "$1" = "start" ]; then
  docker-compose up -d
fi

if [ "$1" = "stop" ]; then
  docker-compose stop
fi

if [ "$1" = "test" ]; then
  echo "Running all tests"
  printf "${CYAN}"
  ./tests/run_all
  printf "${NC}"
fi
